protologbeat:
  address: "127.0.0.1"
  port: 9515
  protocol: udp
  json_mode: true
  merge_fields_to_root: true
  max_msg_size: 8192
  default_es_log_type: protologbeat

#================================ General ======================================
fields_under_root: true

#============================== Template =======================================

setup.template.enabled: true
setup.template.overwrite: false
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
setup.template.json.enabled: true
setup.template.json.path: "${path.config}/protologbeat.template.json"
setup.template.json.name: "protologbeat"

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  enabled: true
  hosts: ["${BEAT_OS_HOST}:${BEAT_OS_PORT}"]
  protocol: "${BEAT_OS_PROTOCOL}"
  username: "${BEAT_HTTP_USERNAME}"
  password: "${BEAT_HTTP_PASSWORD}"
  ssl.verification_mode: "${BEAT_OS_SSL_VERIFY}"
  template.versions.2x.enabled: false

#============================== Dashboards =====================================
# setup.dashboards.enabled: "${BEAT_DASHBOARDS_ENABLED}"
# "setup.dashboards.enabled: false" now because Beats won't import dashboards
# into OpenSearch dashboards (see opensearch-project/OpenSearch-Dashboards#656
# and opensearch-project/OpenSearch-Dashboards#831). setup.template.enabled
# seems to be okay, however.
setup.dashboards.enabled: false
setup.dashboards.directory: "${BEAT_DASHBOARDS_PATH}"
setup.kibana:
  host: "${BEAT_DASHBOARDS_HOST}:${BEAT_DASHBOARDS_PORT}"
  protocol: "${BEAT_DASHBOARDS_PROTOCOL}"
  username: "${BEAT_HTTP_USERNAME}"
  password: "${BEAT_HTTP_PASSWORD}"
  ssl.verification_mode: "${BEAT_DASHBOARDS_SSL_VERIFY}"

#================================ Logging ======================================
logging.metrics.enabled: false
