---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suricata-live-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: suricata-live-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: suricata-live-deployment
    spec:
      containers:
      - name: suricata-live-container
        image: ghcr.io/mmguero-dev/malcolm/suricata:23.12.1
        imagePullPolicy: Always
        stdin: false
        tty: true
        securityContext:
          capabilities:
            add:
              # NET_ADMIN and NET_RAW - to turn on promiscuous mode and capture raw packets
              - NET_ADMIN
              - NET_RAW
              # SYS_NICE - to set process nice values, real-timescheduling policies, I/O scheduling
              - SYS_NICE
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: suricata-env
          - configMapRef:
              name: suricata-live-env
          - configMapRef:
              name: pcap-capture-env
        env:
          - name: SURICATA_DISABLED
            value: "true"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: suricata-live-var-local-catrust-volume
          - mountPath: /var/log/suricata
            name: suricata-live-suricata-logs-volume
          - mountPath: "/opt/suricata/rules/configmap"
            name: suricata-live-custom-rules-volume
          - mountPath: "/opt/suricata/include-configs/configmap"
            name: suricata-live-custom-configs-volume
      initContainers:
      - name: suricata-live-dirinit-container
        image: ghcr.io/mmguero-dev/malcolm/dirinit:23.12.1
        imagePullPolicy: Always
        stdin: false
        tty: true
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/suricata-logs:live"
        volumeMounts:
          - name: suricata-live-suricata-logs-volume
            mountPath: "/data/suricata-logs"
      volumes:
        - name: suricata-live-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: suricata-live-suricata-logs-volume
          persistentVolumeClaim:
            claimName: suricata-claim
        - name: suricata-live-custom-rules-volume
          configMap:
            name: suricata-rules
        - name: suricata-live-custom-configs-volume
          configMap:
            name: suricata-configs